--SELECT PARA VER AS ALTERAÇÕES FEITAS NA TABELA
SELECT * FROM Cidade

--SELECT PARA CONSULTAR O ID DO ESTADO QUE DESEJA ADICIONAR NA TABELA CIDADE
SELECT * FROM Estado

--INSERIR DADOS NA TABELA CIDADE
INSERT INTO Cidade (Id, Nome, EstadoId) VALUES (Id, '', EstadoId)